# Generated by Django 5.0.1 on 2024-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodTrucks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.IntegerField()),
                ("applicant", models.CharField(max_length=200)),
                ("facility_type", models.CharField(max_length=200)),
                ("location_description", models.TextField()),
                ("address", models.TextField()),
                ("food_items", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
